In [1]:
import pandas as pd
import pickle
import seaborn as sns

In [2]:
with open('pickle/mta_data_intra_w.pickle', 'rb') as to_read: #run weighted_delta to generate
    mta_intra_weight = pickle.load(to_read)
    
with open('pickle/mta_data_daily_w.pickle', 'rb') as to_read: #run weighted_delta to generate
    mta_daily_weight = pickle.load(to_read)

In [3]:
mta_daily_weight.head()

,C/A,UNIT,SCP,STATION,LINENAME,DATE,TIME_DELTA,ENTRIES_DELTA,EXITS_DELTA,TOTAL_DELTA,Zipcodes,Percent_Female,Percent_Non_White,Weighted_Traffic
0,A002,R051,02-00-00,59 ST,NQR456W,2019-03-30,1 days,893.0,299.0,1192.0,10022,0.546,-85.4,650.832
1,A002,R051,02-00-00,59 ST,NQR456W,2019-03-30,1 days,893.0,299.0,1192.0,11220,0.495,-29.6,590.040
2,A002,R051,02-00-00,59 ST,NQR456W,2019-03-30,1 days,893.0,299.0,1192.0,11220,0.495,-29.6,590.040
3,A002,R051,02-00-00,59 ST,NQR456W,2019-03-30,1 days,893.0,299.0,1192.0,10022,0.546,-85.4,650.832
4,A002,R051,02-00-00,59 ST,NQR456W,2019-03-30,1 days,893.0,299.0,1192.0,10022,0.546,-85.4,650.832

In [4]:
mta_daily_weight.sort_values('Weighted_Traffic', ascending = False).head(20)

,C/A,UNIT,SCP,STATION,LINENAME,DATE,TIME_DELTA,ENTRIES_DELTA,EXITS_DELTA,TOTAL_DELTA,Zipcodes,Percent_Female,Percent_Non_White,Weighted_Traffic
139665,JFK03,R536,00-00-04,JFK JAMAICA CT1,E,2019-05-11,1 days,74048.0,466740.0,540788.0,11432,0.507,-22.8,274179.516
586855,R227,R131,00-00-02,23 ST,6,2019-05-14,1 days,26076.0,28861.0,54937.0,10010,0.537,-72.8,29501.169
586857,R227,R131,00-00-02,23 ST,6,2019-05-14,1 days,26076.0,28861.0,54937.0,10010,0.537,-72.8,29501.169
586847,R227,R131,00-00-02,23 ST,6,2019-05-14,1 days,26076.0,28861.0,54937.0,10010,0.537,-72.8,29501.169
586852,R227,R131,00-00-02,23 ST,6,2019-05-14,1 days,26076.0,28861.0,54937.0,10010,0.537,-72.8,29501.169
586846,R227,R131,00-00-02,23 ST,6,2019-05-14,1 days,26076.0,28861.0,54937.0,10010,0.537,-72.8,29501.169
586856,R227,R131,00-00-02,23 ST,6,2019-05-14,1 days,26076.0,28861.0,54937.0,10010,0.537,-72.8,29501.169
586851,R227,R131,00-00-02,23 ST,6,2019-05-14,1 days,26076.0,28861.0,54937.0,10010,0.537,-72.8,29501.169
586858,R227,R131,00-00-02,23 ST,6,2019-05-14,1 days,26076.0,28861.0,54937.0,10010,0.537,-72.8,29501.169
586850,R227,R131,00-00-02,23 ST,6,2019-05-14,1 days,26076.0,28861.0,54937.0,10011,0.490,-79.3,26919.130
586854,R227,R131,00-00-02,23 ST,6,2019-05-14,1 days,26076.0,28861.0,54937.0,10011,0.490,-79.3,26919.130
586853,R227,R131,00-00-02,23 ST,6,2019-05-14,1 days,26076.0,28861.0,54937.0,10011,0.490,-79.3,26919.130
586848,R227,R131,00-00-02,23 ST,6,2019-05-14,1 days,26076.0,28861.0,54937.0,10011,0.490,-79.3,26919.130
586849,R227,R131,00-00-02,23 ST,6,2019-05-14,1 days,26076.0,28861.0,54937.0,10011,0.490,-79.3,26919.130
424807,PTH21,R540,01-00-01,PATH WTC 2,1,2019-04-04,1 days,15723.0,10997.0,26720.0,11207,0.547,-10.4,14615.840
612588,R240,R047,00-00-00,GRD CNTRL-42 ST,4567S,2019-05-30,1 days,3029.0,13080.0,16109.0,10017,0.548,-74.4,8827.732
612589,R240,R047,00-00-00,GRD CNTRL-42 ST,4567S,2019-05-30,1 days,3029.0,13080.0,16109.0,10017,0.548,-74.4,8827.732
612586,R240,R047,00-00-00,GRD CNTRL-42 ST,4567S,2019-05-30,1 days,3029.0,13080.0,16109.0,10017,0.548,-74.4,8827.732
612585,R240,R047,00-00-00,GRD CNTRL-42 ST,4567S,2019-05-30,1 days,3029.0,13080.0,16109.0,10017,0.548,-74.4,8827.732
612587,R240,R047,00-00-00,GRD CNTRL-42 ST,4567S,2019-05-30,1 days,3029.0,13080.0,16109.0,10017,0.548,-74.4,8827.732

In [5]:
wgt_daily_station = mta_daily_weight.groupby(['STATION', 'DATE'])['Weighted_Traffic'].sum().reset_index()

In [6]:
wgt_daily_avg = wgt_daily_station.groupby(['STATION'])['Weighted_Traffic'].mean().reset_index()

In [9]:
wgt_daily_top = wgt_daily_avg.sort_values('Weighted_Traffic', ascending=False).reset_index(drop=True)
wgt_daily_top.head()

           STATION  Weighted_Traffic
0            23 ST     992500.244903
1        FULTON ST     810617.239984
2  GRD CNTRL-42 ST     690646.061677
3            86 ST     632487.527419
4   34 ST-PENN STA     524934.854190

In [10]:
with open('pickle/wgt_daily_top.pickle', 'wb') as to_write:
    pickle.dump(wgt_daily_top, to_write)